config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resource :session
  resources :passwords, param: :token
  root "pages#home"
  get "ride-the-bus", to: "pages#ride_the_bus_home"
  get "sbsquares", to: "pages#sbsquares_home"
  get "wordle", to: "pages#wordle_home"
  get "about", to: "pages#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :first_name, :last_name, presence: true
  validates :nickname, presence: true, uniqueness: true
  validates :balance, presence: true, numericality: { greater_than_or_equal_to: 0 }

  # Maybe add a method for display name flexibility
  def display_name
    nickname.present? ? nickname : "#{first_name} #{last_name}"
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_one :profile, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  allow_unauthenticated_access only: %i[ home about ]

  def home
  end

  def ride_the_bus_home
  end

  def sbsquares_home
  end

  def wordle_home
  end

  def about
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy!

    respond_to do |format|
      format.html { redirect_to profiles_path, status: :see_other, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.expect(profile: [ :user_id, :first_name, :last_name, :nickname, :balance ])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Likablegames" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# Include stylesheets from web awesome %>
    <link rel="stylesheet" href="https://early.webawesome.com/webawesome@3.0.0-alpha.13/dist/styles/themes/glossy.css" />
    <link rel="stylesheet" href="https://early.webawesome.com/webawesome@3.0.0-alpha.13/dist/styles/webawesome.css" />
    <link rel="stylesheet" href="https://early.webawesome.com/webawesome@3.0.0-alpha.13/dist/styles/color/default.css"  class="wa-palette" />
    <link rel="stylesheet" href="https://early.webawesome.com/webawesome@3.0.0-alpha.13/dist/styles/utilities/variants.css" />
    <script type="module" src="https://early.webawesome.com/webawesome@3.0.0-alpha.13/dist/webawesome.loader.js"></script>
  </head>

  <body>
    <wa-page mobile-breakpoint="920">

      <%= render(HeaderComponent.new) %>

      <%# Placeholder - this needs to change based on game %>
      <% if false %>
        <%= render NavigationComponent.new(links: [
          { text: "Home", path: root_path },
          { text: "About", path: about_path },
          { text: "Wordle", path: "#" },
          { text: "Ride the Bus", path: "#" },
          { text: "Superbowl Squares", path: "#" }
        ]) %>
      <% end %>

      <main class="wa-body-l">
        <%= yield %>
      </main>

      <%= render(FooterComponent.new) %>
    </wa-page>

    <style>
      wa-page {
        --menu-width: 15rem;
        --aside-width: 15rem;
      }
      wa-page[view='desktop'] {
        [slot*='navigation'] {
          border-inline-end: var(--wa-border-width-s) var(--wa-border-style) var(--wa-color-surface-border);
        }
      }
      wa-page[view='mobile'] {
        --menu-width: auto;
        --aside-width: auto;
      }
    </style>

    <script>
      const sectionAnchors = document.querySelectorAll("[slot*='navigation'] a[href*='#']");
      sectionAnchors.forEach((sectionAnchor) => sectionAnchor.setAttribute("data-drawer", "close"));
    </script>

  </body>
</html>

app/views/pages/about.html.erb
<h1>So what exactly are Likable Games?</h1>
<p>Here is where I insert some killer copy!</p>

app/views/pages/home.html.erb
<h1>Welcome to Likable Games</h1>
<p>Welcome to this site. Currently, none of these games work. Wordle is nearly done. The others are basically just ideas.</p>

<p>I bet I'll get these up before July 4. Let's see...</p>

app/views/pages/ride_the_bus_home.html.erb
<center><h1>Ride the Bus!</h1></center>

<center><p>Let's play some ride the bus. For right now, I'm gonna just tinker with the UI...</p></center>

<div class="wa-stack wa-gap-0" style="background-color: #008000;">
  <div class="wa-span-grid ">
    <div><center><%= image_tag "red.svg", size: "50" %></center></div>
  </div>
  <div class="wa-span-grid wa-heading-xl">
    <div><center>RIDE THE BUS</center></div>
  </div>
  <div class="wa-grid wa-gap-0" style="--min-column-size: 200px;">
    <div class="wa-body-l"><center>Round 1 <%= tag.br %> Red or Black <%= tag.br %> 2x</center></div>
    <div class="wa-body-l"><center>Round 2 <%= tag.br %> Higher or Lower <%= tag.br %> 3x</center></div>
    <div class="wa-body-l"><center>Round 3 <%= tag.br %> Inside or Outside <%= tag.br %> 4x</center></div>
    <div class="wa-body-l"><center>Round 4 <%= tag.br %> Suit <%= tag.br %> 20x</center></div>
  </div>
  <div class="wa-grid wa-gap-0" style="--min-column-size: 200px;">
    <div><center><%= image_tag "diamonds_3.svg", size: "50" %></center></div>
    <div><center><%= image_tag "hearts_queen.svg", size: "50" %></center></div>
    <div><center><%= image_tag "spades_ace.svg", size: "50" %></center></div>
    <div><center><%= image_tag "clubs_8.svg", size: "50" %></center></div>
  </div>
  <div class="wa-grid wa-gap-0" style="--min-column-size: 50px;">
    <div><center>Player 1 <%= tag.br %>Bet: $10</center></div>
    <div><center>Player 2 <%= tag.br %>Bet: $10</center></div>
    <div><center>Player 3 <%= tag.br %>Bet: $10</center></div>
    <div><center>Player 4 <%= tag.br %>Bet: $10</center></div>
    <div><center>Player 5 <%= tag.br %>Bet: $10</center></div>
    <div><center>Player 6 <%= tag.br %>Bet: $10</center></div>
    <div><center>Player 7 <%= tag.br %>Bet: $10</center></div>
  </div>
</div>

app/views/pages/sbsquares_home.html.erb
<h1 style="text-align: center;">Super Bowl Squares!</h1>

<p style="text-align: center;">For now, just playing with the UI...</p>

<div class="wa-stack wa-gap-xs">
  <p class="wa-heading-3xl" style="text-align: center;">PATRIOTS</p>

    <div class="wa-cluster wa-gap-xs" style="justify-content: center;">
      <div style="width: 7ch;"></div>
        <% 10.times do %>
          <div style="width: 7ch; display: flex; justify-content: center;">
            <wa-icon name="x"></wa-icon>
          </div>
        <% end %>
    </div>

    <% 10.times do %>
      <div class="wa-cluster wa-gap-xs" style="justify-content: center;">
        <wa-icon name="y" style="width: 7ch; display: flex; justify-content: center; align-items: center;"></wa-icon>
        <% 10.times do %>
          <wa-input style="width: 7ch; height: 7ch;"></wa-input>
        <% end %>
      </div>
    <% end %>
</div>

app/views/pages/wordle_home.html.erb
<h1 style="text-align: center;">Let's play Wordle!</h1>

<p style="text-align: center;">For now, just playing with the UI...</p>

<div class="wa-stack wa-gap-xs">
  <div class="wa-cluster wa-gap-xs" style="justify-content: center;">
    <wa-input style="width: 5ch;" autofocus="true" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
  </div>
  <div class="wa-cluster wa-gap-xs" style="justify-content: center;">
    <wa-input style="width: 5ch;" autofocus="true" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
  </div>
  <div class="wa-cluster wa-gap-xs" style="justify-content: center;">
    <wa-input style="width: 5ch;" autofocus="true" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
  </div>
  <div class="wa-cluster wa-gap-xs" style="justify-content: center;">
    <wa-input style="width: 5ch;" autofocus="true" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
  </div>
  <div class="wa-cluster wa-gap-xs" style="justify-content: center;">
    <wa-input style="width: 5ch;" autofocus="true" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
  </div>
  <div class="wa-cluster wa-gap-xs" style="justify-content: center;">
    <wa-input style="width: 5ch;" autofocus="true" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
    <wa-input style="width: 5ch;" maxlength="1"></wa-input>
  </div>
</div>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :nickname, style: "display: block" %>
    <%= form.text_field :nickname %>
  </div>

  <div>
    <%= form.label :balance, style: "display: block" %>
    <%= form.number_field :balance %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
  <p>
    <strong>User:</strong>
    <%= profile.user_id %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= profile.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= profile.last_name %>
  </p>

  <p>
    <strong>Nickname:</strong>
    <%= profile.nickname %>
  </p>

  <p>
    <strong>Balance:</strong>
    <%= profile.balance %>
  </p>

</div>

app/views/profiles/edit.html.erb
<% content_for :title, "Editing profile" %>

<h1>Editing profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Show this profile", @profile %> |
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Profiles" %>

<h1>Profiles</h1>

<div id="profiles">
  <% @profiles.each do |profile| %>
    <%= render profile %>
    <p>
      <%= link_to "Show this profile", profile %>
    </p>
  <% end %>
</div>

<%= link_to "New profile", new_profile_path %>

app/views/profiles/new.html.erb
<% content_for :title, "New profile" %>

<h1>New profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @profile %>

<div>
  <%= link_to "Edit this profile", edit_profile_path(@profile) %> |
  <%= link_to "Back to profiles", profiles_path %>

  <%= button_to "Destroy this profile", @profile, method: :delete %>
</div>